- hosts: localhost
  connection: local
  tasks:
    - name: Create a new host or update an existing host's info
      local_action:
        module: zabbix_host
        server_url: http://localhost/zabbix
        login_user: Admin
        login_password: zabbix
        host_name: ExampleHost
        host_groups:
          - Linux servers
        link_templates:
          - Template OS Linux
        status: enabled
        state: present
        interfaces:
          - type: 1
            main: 1
            useip: 1
            ip: 192.168.10.194
            dns: ""
            port: 10050
